# 基础配置
model_name: "littlellm"
vocab_size: 50257

# 模型结构
block_size: 512 #上下文长度
n_layer: 8 # 模型层数
n_head: 12 # 注意力头
n_embed: 768
drop_out: 0.1
head_size: 64 #int = n_embed//n_head 需要显式说明为整数，否则会报浮点数错误
