# 训练参数配置
lr: 5e-5
batch_size: 4
max_seq_length: 512
pre_dataset_path: 'utils\data_gene\output_data.jsonl'
sft_dataset_path: 'utils\data_gene\sft_mini_512.jsonl'
epochs: 5


optimizer:
  name: "adamw"
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01